import { useState, useEffect } from "react";
import axios from "axios";
import Head from "next/head";
import { Center, Container, Grid, Heading, VStack } from "@chakra-ui/react";
import { Header } from "../components/Header/Header";
import { Footer } from "../components/Footer/Footer";
import { ProductCard } from "../components/ProductCard/ProductCard";

export default function Home() {
  const [products, setProducts] = useState([]);
  const [error, setError] = useState(false);

  useEffect(() => {
    axios
      .get("/api/products")
      .then((res) => setProducts(res.data.products))
      .catch((error) => setError(true));
  }, []);

  return (
    <main data-testid="product-list">
      <Head>
        <title>Watch Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <VStack alignItems="center" justifyContent="center">
        <Container paddingY={10}>
          <Center>
            <Heading>Trending</Heading>
          </Center>
        </Container>

        <Container maxWidth="container.xl">
          <Grid templateColumns="repeat(4, 1fr)" gap={4}>
            {products.map((product) => (
              <ProductCard product={product} key={product.id} />
            ))}
          </Grid>
        </Container>
      </VStack>

      <Footer />
    </main>
  );
}
